---
# ansible-galaxy install -r roles/requirements.yml -p ./roles/ --force -vvv

- src: git@bitbucket.org:boomii/ansible-role-jmxutil.git
  scm: git
  version: master
  name: galaxy-ansible-role-jmxutil

- src: geerlingguy.nodejs
  version: master
  name: galaxy-geerlingguy.nodejs

- src: geerlingguy.clamav
  name: galaxy-geerlingguy.clamav

# - src: geerlingguy.docker
#   name: galaxy-geerlingguy.docker

# - src: git@github.com:otteydw/ansible-role-docker.git
#   scm: git
#   version: allow_override_ansible_distribution_release
#   name: galaxy-ottey.docker


- src: geerlingguy.dotfiles
  name: galaxy-geerlingguy.dotfiles

- src: huxoll.azure-cli
  name: galaxy-huxoll.azure-cli

- src: git@bitbucket.org:boomii/ansible-role-agent-newrelic-infrastructure.git
  scm: git
  # version: main
  name: galaxy-ansible-role-agent-newrelic-infrastructure
