---
# ansible-galaxy install -r roles/requirements.yml -p ./roles/ --force -vvv

- src: git@bitbucket.org:boomii/ansible-role-jmxutil.git
  scm: git
  version: master
  name: galaxy-ansible-role-jmxutil

- src: https://github.com/geerlingguy/ansible-role-nodejs.git
  version: master
  name: galaxy-geerlingguy.nodejs

- src: geerlingguy.clamav
  name: galaxy-geerlingguy.clamav

- src: geerlingguy.docker
  name: galaxy-geerlingguy.docker

- src: geerlingguy.dotfiles
  name: galaxy-geerlingguy.dotfiles

- src: huxoll.azure-cli
  name: galaxy-huxoll.azure-cli
