---
- hosts: localhost

  tasks:

    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    # # https://www.linuxbabe.com/ubuntu/install-nvidia-driver-ubuntu-18-04
    # - name: Install Graphics Drivers PPA repo
    #   apt_repository:
    #       repo: ppa:graphics-drivers/ppa
    #       state: present
    #   become: yes

    - name : Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - cpanminus
          - curl
          - gnome-tweaks
          - jq
          - libappindicator-dev   # http://tipsonubuntu.com/2018/05/25/re-enable-shutter-app-icon-ubuntu-18-04-system-tray/
          - nmap
          # - nvidia-driver-396
          - python-pip
          - shutter
          - terminator
      become: yes

    - name: Install Gtk2::AppIndicator
      cpanm:
        name: Gtk2::AppIndicator  # http://tipsonubuntu.com/2018/05/25/re-enable-shutter-app-icon-ubuntu-18-04-system-tray/
      become: yes

    - name: Check if Visual Studio Code is installed
      shell: dpkg-query -W 'code'
      ignore_errors: True
      changed_when: false
      register: is_code

    - name : Install Visual Studio Code
      apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868
      become: yes
      when: is_code is failed

    - name: Check if Discord is installed
      shell: dpkg-query -W 'discord'
      ignore_errors: True
      changed_when: false
      register: is_discord 

    - name : Install Discord
      apt:
        deb: https://discordapp.com/api/download?platform=linux&format=deb
      become: yes
      when: is_discord is failed

    - name: Check if Slack is installed
      shell: dpkg-query -W 'slack-desktop'
      ignore_errors: True
      changed_when: false
      register: is_slack

    - name : Install Slack
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.0-amd64.deb
      become: yes
      when: is_slack is failed

    - name: Check if Dropbox is installed
      shell: dpkg-query -W 'dropbox'
      ignore_errors: True
      changed_when: false
      register: is_dropbox

    - name : Install Dropbox
      apt:
        deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
      become: yes
      when: is_dropbox is failed

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: yes

    # Set of symlinks required for VMWare Horizon Client
    - file:
        src: /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
        dest: /usr/lib/x86_64-linux-gnu/libgstreamer-0.10.so.0
        owner: root
        group: root
        state: link
      become: yes

    - file:
        src: /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0
        dest: /usr/lib/x86_64-linux-gnu/libgstapp-0.10.so.0
        owner: root
        group: root
        state: link
      become: yes

    - file:
        src: /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
        dest: /usr/lib/x86_64-linux-gnu/libgstbase-0.10.so.0
        owner: root
        group: root
        state: link
      become: yes

    - lineinfile:
        path: ~/.config/terminator/config 
        regexp: '.*size =.*'
        insertafter: '.*type = Window'
        line: '      size = 2000, 1000'
        create: no
        
    - name: Install pip packages
      pip:
        name: "{{ packages }}"
      vars:
        packages:
          - mdv # View Markdown Files in Terminal
      become: yes
