---
- hosts: localhost

  tasks:

    - name: Install Spotify Key
      apt_key:
        url: "https://download.spotify.com/debian/pubkey.gpg"
        state: present
      become: yes

    - name: Add Spotify repo
      apt_repository:
        repo: "deb http://repository.spotify.com stable non-free"
        state: present
      become: yes

    # https://yktoo.com/en/software/sound-switcher-indicator/
    - name: Add Sound Switcher Repository
      apt_repository:
        repo: "ppa:yktooo/ppa"
        state: present
      become: yes

    # https://itsfoss.com/best-linux-screen-recorders/
    - name: Add OBS-Studio Repository
      apt_repository:
        repo: "ppa:obsproject/obs-studio"
        state: present
      become: yes

    - name: Add Lutris Repository
      apt_repository:
        repo: "ppa:lutris-team/lutris"
        state: present
      become: yes

    - name: Pre-create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0750'
      with_items:
        - ~/.config/
        - ~/.config/terminator
        - ~/.config/gtk-3.0
        - ~/opt/
        - ~/opt/bin

    - name: Update the apt cache if the last update was more than 1 hour ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name : Install deb packages
      apt:
        name:
          - adb # Android Debugging
          - alpine
          - apt-transport-https
          - awscli
          - black # python code formatter
          - boxes
          - ca-certificates
          - cpanminus
          - curl
          - dirmngr # AZ cli
          - filezilla
          - ffmpeg  # youtube-dl
          - figlet
          - gimp
          - git-extras
          - gnome-tweaks
          - gnupg-agent
          - htop
          - indicator-sound-switcher  # https://yktoo.com/en/software/sound-switcher-indicator/
          - ipcalc
          - jq
          - libappindicator-dev   # http://tipsonubuntu.com/2018/05/25/re-enable-shutter-app-icon-ubuntu-18-04-system-tray/
          - lsb
          - lutris
          - lsb-release # AZ cli
          - mutt
          - mysql-client
          - net-tools
          - nmap
          - obs-studio
          - openvpn-systemd-resolved
          - p7zip
          - pwgen
          - python3-pip
          - python3-tk  # tkinter
          - python3-venv
            #- python-pip
          - scrcpy  # display and control of Android devices
          - screen
          - software-properties-common
          - speedtest-cli
          - spotify-client
          - terminator
          - transmission
          - unrar
          - vlc
          - whois
          - wireshark
          # https://boomi.slack.com/archives/G0UUG0PFS/p1550855956035300
          # sudo apt-get install --install-recommends linux-generic-hwe-18.04 xserver-xorg-hwe-18.04
          - linux-generic-hwe-18.04
          - xserver-xorg-hwe-18.04
          # tesseract OCR
          - tesseract-ocr
          - libtesseract-dev
      become: yes

    - name: Install snap packages
      snap:
        name:
          - gitkraken
          - postman
      become: yes

    # Set of symlinks required for VMWare Horizon Client
    - name: Symlinks required for VMWare Hortizon Client
      file:
        src: "/usr/lib/x86_64-linux-gnu/{{ item }}-1.0.so.0"
        dest: "/usr/lib/x86_64-linux-gnu/{{ item }}-0.10.so.0"
        owner: root
        group: root
        state: link
      with_items:
        - libgstreamer
        - libgstapp
        - libgstbase
      become: yes

    - name: Add setting to Terminator config
      lineinfile:
        path: ~/.config/terminator/config
        regexp: '.*size =.*'
        insertafter: '.*type = Window'
        line: '      size = 2000, 1000'
        create: no

    # gtk.css from http://blog.nabam.net/workstation/2017/09/15/terminator_tabs/
    - name: GTK CSS (Used for terminator)
      copy:
        src: "gtk.css"
        dest: "~/.config/gtk-3.0/gtk.css"

    - name: Install pip packages
      pip:
        name: "{{ packages }}"
      vars:
        packages:
          - boardgamegeek2 # purely for my own enjoyment
          - mdv # View Markdown Files in Terminal
          - youtube_dl
      become: yes

    # Set fs.inotify.max_user_watches required for larger VS code workspaces
    # Default: 8192
    # https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
    - name: Set fs.inotify.max_user_watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: 524288
        sysctl_set: yes
        state: present
        reload: yes
      become: yes

    # https://github.com/magicmonty/bash-git-prompt
    - name: Get git bash prompt
      git:
        repo: 'https://github.com/magicmonty/bash-git-prompt.git'
        dest: ~/.bash-git-prompt
        depth: 1
        update: no

    - name: Flameshot Print Screen Hotkey Replacement
      copy:
        src: "flameshot-hotkey.sh"
        dest: "~/opt/bin/flameshot-hotkey.sh"
        mode: 0700

    - name: Install Slack
      snap:
        name: slack
        classic: yes
      become: yes

    - name: Create a python2 virtualenv
      pip:
        name: pip
        virtualenv: ~/opt/p2env
        virtualenv_python: python2

    - name: Allow user to run openvpn via sudo without password
      template:
        src: openvpn-sudoers.j2
        dest: /etc/sudoers.d/10-openvpn
        validate: "visudo -cf %s"
        mode: 0440
      become: yes

- hosts: localhost

  roles:
    - role: dellzoom
    - role: discord
    - role: docker
      #    - role: dropbox
    - role: flameshot
    - role: pyenv
    - role: vagrant

    - role: virtualbox
      virtualbox_apt_distribution_release: eoan # Force Ubuntu 19.10's VirtualBox repo even on Ubuntu 20.04 (because "focal" is not yet available)

    - role: vscode

    - role: galaxy-geerlingguy.clamav
      become: true

    # - role: galaxy-geerlingguy.docker
    # - role: galaxy-ottey.docker
    #   docker_apt_distribution_release: bionic # Force Ubuntu 19.10's Docker repo even on Ubuntu 20.04 (because "focal" is not yet available)
    #   docker_users:
    #     - dottey
    #   become: true

    # - role: galaxy-huxoll.azure-cli
    #   become: true

    - role: galaxy-ansible-role-jmxutil
      boomi_user_name: dottey
      boomi_group_name: dottey

    - role: galaxy-geerlingguy.nodejs
      nodejs_version: "13.x"
      become: true

    - role: galaxy-geerlingguy.dotfiles
      dotfiles_repo: git@github.com:otteydw/dotfiles.git
      dotfiles_repo_local_destination: ~/git/dotfiles
      dotfiles_files:
        - .bashrc
        - .gitconfig
        - .gitignore
        - .screenrc
        - .vimrc

  tasks:
    - name: Install elasticdump
      npm:
        name: elasticdump
        global: true
      become: true

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: yes
