---
- hosts: localhost

  tasks:

    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    # # https://www.linuxbabe.com/ubuntu/install-nvidia-driver-ubuntu-18-04
    # - name: Install Graphics Drivers PPA repo
    #   apt_repository:
    #       repo: ppa:graphics-drivers/ppa
    #       state: present
    #   become: yes

    - name : Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - cpanminus
          - gnome-tweaks
          - libappindicator-dev   # http://tipsonubuntu.com/2018/05/25/re-enable-shutter-app-icon-ubuntu-18-04-system-tray/
          # - nvidia-driver-396
          - shutter
          - terminator
      become: yes

    - name: Install Gtk2::AppIndicator
      cpanm:
        name: Gtk2::AppIndicator  # http://tipsonubuntu.com/2018/05/25/re-enable-shutter-app-icon-ubuntu-18-04-system-tray/
      become: yes

    - name: Check if Visual Studio Code is installed
      shell: dpkg-query -W 'code'
      ignore_errors: True
      changed_when: false
      register: is_code

    - name : Install Visual Studio Code
      apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868
      become: yes
      when: is_code is failed

    - name: Check if Discord is installed
      shell: dpkg-query -W 'discord'
      ignore_errors: True
      changed_when: false
      register: is_discord 

    - name : Install Discord
      apt:
        deb: https://discordapp.com/api/download?platform=linux&format=deb
      become: yes
      when: is_discord is failed

    - name: Check if Slack is installed
      shell: dpkg-query -W 'slack-desktop'
      ignore_errors: True
      changed_when: false
      register: is_slack

    - name : Install Slack
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.0-amd64.deb
      become: yes
      when: is_slack is failed

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: yes

      # dpkg-query -W slack-desktop
