---
- hosts: localhost

  tasks:
          - name : Install packages
            apt:
                    name: "{{ packages }}"
            vars:
                    packages:
                            - shutter
                            - terminator

          - name : Install Visual Studio Code
            apt:
                    deb: https://go.microsoft.com/fwlink/?LinkID=760868
            become: yes
