- name: Install HashiCorp Key
  apt_key:
    data: "{{ lookup('file', 'hashicorp.gpg') }}"
    id: 51852D87348FFC4C
  become: yes

- name: Check if Vagrant is installed
  shell: dpkg-query -W 'vagrant'
  ignore_errors: True
  changed_when: false
  register: is_vagrant_installed

- name : Install Vagrant
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  become: yes
  when: is_vagrant_installed is failed
