- name: Install VirtualBox Key from Oracle
  apt_key:
    url: "{{ virtualbox_apt_gpg_key }}"
    state: present
  ignore_errors: "{{ virtualbox_apt_ignore_key_error }}"
  become: yes

- name: Add VirtualBox repo
  apt_repository:
    repo: "{{ virtualbox_apt_repository }}"
    state: present
  become: yes

- name : Install VirtualBox
  apt:
    name: virtualbox-6.1
  become: yes
