
- name : Install deb packages
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: yes

- name: Install GPG Key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: yes

# TODO: focal = lsb_release -cs
- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  become: yes
  register: docker_repo

- name : Install docker packages
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes # TODO: Update only when above changed
  become: yes